### ISSUE TITLE
ZED 1.0?

### ISSUE THREAD

**Issue by jeremy-a** [Myzhar/ros_simple_zed_cuda_driver#4]
The CMakeLists.txt tries to find ZED version 1.0. AFAI, ZED 1.0 isn't released or maybe I'm looking in the wrong place. I only see 0.9.2 here (https://www.stereolabs.com/developers/#start_anchor). I'm using the Jetson TK1 version of ZED SDK.

**Comment by Myzhar** [comment]
Yes... you are right. It's an issue due to a initial mismatch, Corrected
